twitter-to-kafka-service:
    twitter-keywords:
        - Java
        - Spring
        - Kafka
        - Microservices
        - Docker
    welcome-message: Welcome to the Twitter to Kafka Service
    enable-mock-tweets: true
    mock-tweet-min-length: 5
    mock-tweet-max-length: 140
    mock-tweet-sleep-ms: 1000 

retry-config:
    initial-interval-ms: 1000
    max-interval-ms: 10000
    multiplier: 2.0
    max-attempts: 3
    sleep-time-ms: 2000

kafka-config:
    bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
    schema-registry-url: localhost:8081
    schema-registry-url-key: schema.registry.url
    topic-name: twitter-topic
    topic-names-to-create: 
        - twitter-topic
    num-partitions: 3
    replication-factor: 3

kafka-producer-config:
    acks: all
    retry-count: 0
    request-timeout-ms: 15000
    batch-size: 16384
    batch-size-boost-factor: 1
    linger-ms: 0
    compression-type: snappy
    key-serializer: org.apache.kafka.common.serialization.LongSerializer
    value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer